language: node_js
node_js:
  - 10
  - node
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn install
install: true
matrix:
  fast_finish: true
branches:
  only:
    - master
    - /^release-.*/

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: react-scripts-ts test --env=jsdom --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
